namespace StockTimeMachine;

// Single source of the methodology copy: the /methodology endpoint AND the
// explainer's grounding corpus read from here, so UI copy, API copy, and AI
// grounding can never drift apart. Edit text here once; everything follows.
public static class MethodologyContent
{
    public const string Title = "Methodology";

    public const string Intro = "Stock Time Machine reconstructs what an investor could have known at a specific moment in market history. We do not predict; we remember with discipline.";

    public static readonly IReadOnlyList<(string Heading, string Body)> Sections = new List<(string Heading, string Body)>
    {
        ("Temporal Boundary", "Each historical date maps to a strict cutoff at 23:59:59 US/Eastern on that calendar date. SEC filings are eligible by their SEC acceptance timestamp, news by publication time, and daily prices by trading day. Anything after the cutoff is excluded from the historical view and shown separately as outcome data."),
        ("Providers", "Historical OHLCV prices come from Alpha Vantage. SEC filings come from SEC EDGAR. Company identity is resolved from our directory, SEC EDGAR, then Finnhub. Current (delayed) quotes for the reveal come from Finnhub. API keys stay on the server and are never sent to the browser."),
        ("News Sources", "You choose the news source for each investigation: Alpha Vantage, GDELT, or MarketAux (entity-tagged finance news with per-article timestamps; free tier 100 requests/day, recent-years coverage — January 2020 returns empty while January 2025 returns results). GDELT is served by GDELT Cloud (entity-anchored stories with article evidence; corpus starts March 2026, so older windows return empty; each fetch takes the newest 100 rows of the trailing 7-day window, so unusually busy weeks can still truncate) when a server-side key is configured, otherwise the keyless GDELT Project archive. The selected source is shown on every snapshot and its results carry source attribution. Sources are never mixed and never silently substituted: if the selected source has no coverage, you see an honest empty state, not another provider's data in disguise. Throttled sources are retried with backoff honoring Retry-After (up to 3 retries) and spaced by request pacing; repeated failures degrade honestly, and one failed fetch per investigation covers all moves instead of re-hammering."),
        ("Determinism", "Given the same company, date, news source, and persisted data, the snapshot engine returns the same result. Snapshots are composed from stored rows; the database is always checked before any external call."),
        ("Simulation", "The 'What if?' simulation uses raw, unadjusted prices. Stock splits and dividends are not factored into entry or exit prices. The disclaimer is always shown."),
        ("Key Moves — Last 100 Trading Days", "Significant movements are detected deterministically over the last 100 trading days before your date (minimum 30 required, else the lens reports insufficient history). Score = 0.5 × min(|z|/3, 1) + 0.3 × min(max(volumeRatio − 1, 0)/4, 1) + 0.2 × rangeBreak, where z is the daily-return z-score versus the trailing 20 days, volumeRatio is volume versus the trailing-20-day median, and rangeBreak is the fractional close beyond the trailing-20-day high/low (×20, so a 5% break scores full). Top 5 by score; ties break by later date, then larger move. A 0.05% daily volatility floor keeps perfectly flat windows from hiding genuine spikes. Flags: spike (z > 2), plunge (z < −2), high-volume (> 2.5× median), breakout/breakdown. Ranking statistics use double precision for ordering only — every displayed price is a real decimal close. Each move carries only evidence available by its own date cutoff; proximity in time is never presented as causation. News is DB-first, but a non-empty cache never shadows later coverage: when the newest cached row predates the latest move by over 7 days, one live refresh runs per investigation."),
        ("Decision Uncertainty Index", "A transparent 0–100 gauge of how thin or conflicting the knowable evidence is (higher = more uncertain). Score = 100 × (0.4 × evidence-sparsity + 0.3 × sentiment-dispersion + 0.3 × volatility-level), where sparsity compares evidence items against a full window, dispersion is the std of available per-entity sentiment scores scaled by 0.5, and volatility is annualized window volatility scaled by 50%. Fewer than 2 scored articles contributes 0.5 flagged as unknown — missing sentiment never reads as consensus. Every term is displayed alongside the score; there are no hidden inputs and no action thresholds."),
        ("Market Regimes", "Each analyzed day is labeled calm, normal, or tense from its trailing-20-day annualized volatility, tertiled within that investigation window only — never against absolute thresholds, so regimes are comparable across eras only relatively. Days with fewer than 10 prior closes read warming (insufficient trailing data). Tense stretches shade the moves timeline background. Regimes describe realized volatility; they predict nothing and trigger no action."),
        ("Sentiment Divergence", "For each key move, scored news sentiment is compared against the price direction: same sign reads agree, opposite signs disagree, mean within ±0.1 reads neutral, and fewer than two scored articles reads unknown (single scores are noise, never consensus). Scores come from providers that supply per-entity sentiment; rows without scores are ignored, not zero-filled. A disagreement is a contrarian lens for investigation, never a prediction and never evidence of causation."),
        ("Information Arrival Map", "For each key move, the arrival cascade lists when each information layer — regulatory filings, news, social discussion — first carried something knowable about that move, with lags measured against the earliest layer. Timestamps come from the evidence itself (filing dates, publication instants); GDELT Cloud items resolve to calendar days. A silent layer means no evidence was found there, never that nothing existed. Ordering in time is observation, not causation."),
        ("Narrative Topics", "The narratives endpoint clusters up to 60 cached articles (predominantly English) from the selected news source by keyword overlap: TF-IDF vectors (stopwords removed, no stemming) compared by cosine similarity, merged by greedy agglomerative clustering at a 0.25 similarity threshold. Each cluster is labeled by its three highest-weight terms and illustrated with its most distinctive article — labels name shared vocabulary, not meaning, and never imply events, causes, or importance. Non-English strays surface as their own threads rather than corrupting others. Clustering runs over cached rows only, so it costs zero API quota and is fully deterministic for a given database state; an empty cache yields an honest empty state. Coverage gaps in the underlying source propagate here unchanged."),
        ("AI Cluster Briefs", "Threads may carry an AI-generated brief: Gemini embeddings decide thread membership, and a Gemini Flash model summarizes grounded article text (Jina Reader bodies where fetchable, otherwise stored titles and descriptions) under a prompt that roleplays the investigation date, demands per-claim citations, and bans causation, prediction, and outside knowledge. Briefs appear for multi-article threads only (largest 8). They are NON-deterministic, may contain hindsight leaking from post-cutoff training data, and are labeled as AI-generated wherever shown. Embeddings still decide membership while shared terms name each thread, so labels stay explainable. Any AI failure degrades to the deterministic TF-IDF path, and the response states which method produced it. Scale guards: over-long articles are chunked and mean-pooled for embeddings (never silently truncated), and thread text past the model's input budget is briefed in batches then synthesized by a final reduce call with global citation numbering preserved. All AI calls share a 30,000-tokens-per-minute budget that waits instead of failing, plus request-rate pacing for per-minute request ceilings. Embedding vectors persist per article and model, so repeat investigations reuse vectors instead of re-spending quota. The evidence copilot (filing summaries, article contrast, uncertainty explainers, English gists) reuses the same containment contract on demand, never automatically; the conclusion reviewer checks the user's own note against cited evidence and reports supported/unsupported/unclear per claim without authoring conclusions."),
        ("Limitations", "We do not claim complete historical news coverage: absence of coverage does not mean absence of events. We do not adjust for splits or dividends. We do not provide same-day tick data or intraday precision. One provider failing never destroys an investigation — affected sections are marked unavailable."),
    };

    // Deterministic retrieval for the explainer: rank sections by shared
    // vocabulary with the question (same tokenizer as clustering labels).
    // Pure and unit-tested; the model only ever sees the top-ranked sections.
    public static List<(string Heading, string Body)> Retrieve(string question, int take = 3)
    {
        var query = new HashSet<string>(
            TopicClustering.Tokenize(question), StringComparer.OrdinalIgnoreCase);
        if (query.Count == 0)
            return new List<(string Heading, string Body)>();
        return Sections
            .Select(s => (Section: s, Score: new HashSet<string>(
                TopicClustering.Tokenize(s.Heading + " " + s.Body), StringComparer.OrdinalIgnoreCase)
                .Intersect(query).Count()))
            .Where(x => x.Score > 0)
            .OrderByDescending(x => x.Score)
            .Take(take)
            .Select(x => x.Section)
            .ToList();
    }
}
